name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: build
            command: make build
          - name: embedded_app fmt
            path: embedded_app
            command: cargo fmt --all -- --check
          - name: embedded_app clippy
            path: embedded_app
            command: cargo clippy --all-features --workspace -- -D warnings
          - name: common fmt
            path: common
            command: cargo fmt --all -- --check
          - name: common clippy
            path: common
            command: cargo clippy --all-features --workspace -- -D warnings
          - name: frontend fmt
            path: frontend
            command: cargo fmt --all -- --check
          - name: frontend clippy
            path: frontend
            command: cargo clippy --all-features --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32s3
          ldproxy: false
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            embedded_app
            common
            frontend
      - name: Run command
        working-directory: ${{ matrix.path }}
        run: ${{ matrix.command }}
